version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ../mysql-volume:/var/lib/mysql
    networks:
      - mysql-network

volumes:
  mysql-volume:
    driver: local

networks:
  mysql-network:
    driver: bridge